package wasm-os:system;

world system {
    import debug-print: func(message: string);
    import get-pid: func() -> s32;
    import get-parent-pid: func() -> s32;
    import spawn: func(path: string) -> s32;
    import exit: func(code: s32);
    import sleep: func(seconds: f64);
    import send-event: func(name: string, data: list<u8>, pid: s32) -> s32;
    import get-event-data: func(length: u32) -> list<u8>;
    import get-event-sender: func() -> s32;
    import add-event-handler: func(name: string) -> s32;
    import remove-event-handler: func(name: string) -> s32;
    import set-process-name: func(name: string) -> s32;
    import get-process-label: func() -> string;
    import get-pid-by-name: func(name: string) -> s32;
    import yield-now: func();
}
